name: Publish to NPM

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        environment: Publish
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6
              with:
                  cache: npm
                  node-version: '24'
                  registry-url: https://registry.npmjs.org

            - run: npm ci --ignore-scripts

            - name: Publish (beta)
              if: needs.environment.outputs.CI_ENV == 'beta'
              run: npm publish --tag beta --access restricted

            - name: Publish (production)
              if: needs.environment.outputs.CI_ENV == 'production'
              run: npm publish --access restricted
